services:
  ros-template:
    image: ghcr.io/rosblox/ros-template:humble
    volumes:
      - type: bind
        source: /opt/ros/humble_copy
        target: /opt/ros/humble_copy    
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    network_mode: "host"
    ipc: host
    pid: host
    environment:
      - UID=${HOST_UID}
      - ROS_DOMAIN_ID
    command: su - ros --whitelist-environment=ROS_DOMAIN_ID /run.sh
